name: geek
description: A new Flutter project.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text:
  cached_network_image: 2.5.1
  equatable: ^1.2.5
  path_provider: ^2.0.1
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  font_awesome_flutter:
  google_fonts:
  google_sign_in: ^4.0.16
  json_path: ^0.2.1
  rxdart: ^0.25.0
  sign_in_with_apple: ^2.5.4
  dropdown_formfield: ^0.1.3
  url_launcher:
  http:
  loading_animations: ^2.1.0
  sqflite: ^2.0.0+3
dev_dependencies:

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
  